import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Brain,
    ChevronDown,
    ChevronRight,
    Cpu,
    Activity,
    Copy,
    Check,
    ExternalLink,
    Info,
    Settings2,
    ShieldCheck,
    MessageSquare,
    Zap,
    Share2
} from 'lucide-react';
import Tier1Evidence from './Tier1Evidence';
import Tier2Mechanism from './Tier2Mechanism';
import Tier3Causality from './Tier3Causality';
import Tier4Temporal from './Tier4Temporal';
import ConfidenceTracker from './ConfidenceTracker';
import { Tooltip, getConfidenceNarrative } from './UIUtils';

/**
 * NutriIntelligencePanel
 * 
 * The root container for the Tier-Aware Intelligence Transparency UI.
 * Features:
 * - Progressive Disclosure (Collapsible)
 * - Claim Selector (Multi-claim support with scroll logic)
 * - Expert Mode Toggle (Friendly vs Clinical)
 * - Reasoning Integrity Banner (Psychological Trust)
 * - Shareable Reasoning Summary (Human-readable export)
 */
const NutriIntelligencePanel = React.memo(({ uiTrace, expertModeDefault = false }) => {
    const [isOpen, setIsOpen] = useState(false);
    const [isExpertMode, setIsExpertMode] = useState(expertModeDefault);
    const [selectedClaimIdx, setSelectedClaimIdx] = useState(0);
    const [copied, setCopied] = useState(false);
    const [shared, setShared] = useState(false);

    useEffect(() => {
        // Persist Expert Mode if user toggles it
        const savedMode = localStorage.getItem('nutri_expert_mode');
        if (savedMode !== null) {
            setIsExpertMode(savedMode === 'true');
        }
    }, []);

    const toggleExpertMode = (e) => {
        e.stopPropagation();
        const newMode = !isExpertMode;
        setIsExpertMode(newMode);
        localStorage.setItem('nutri_expert_mode', newMode);
    };

    const handleClaimSelect = (idx) => {
        setSelectedClaimIdx(idx);
        const content = document.getElementById(`trace-content-${uiTrace.id}`);
        if (content) content.scrollIntoView({ behavior: 'smooth', block: 'start' });
    };

    const handleCopy = useCallback(() => {
        const text = JSON.stringify(uiTrace, null, 2);
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    }, [uiTrace]);

    // 🚀 Shareable Summary Generator
    const generateShareableSummary = useCallback(() => {
        const current = uiTrace.claims[selectedClaimIdx] || uiTrace.claims[0];
        const summary = `
Nutri Reasoning Summary
------------------------
Claim: ${current.text}
Status: ${current.isVerified ? 'VERIFIED' : 'ASSEMBLING EVIDENCE'}
Confidence: ${Math.round(current.confidence * 100)}% (${getConfidenceNarrative(current.confidence)})

Key Mechanism:
${current.mechanism?.steps?.map(s => `→ ${s.entity_name}: ${s.description}`).join('\n') || 'General Knowledge Synthesis'}

Safety & Context:
- Applicability: ${Math.round(uiTrace.causality.applicability * 100)}%
- Risks: ${uiTrace.causality.riskCount > 0 ? 'Clinical Guardrails Active' : 'Low Risk'}
- Turn: Turn ${uiTrace.temporal.turn} (${current.temporalMeta.label})

Rationale:
"${current.decisionMeta.reason}"

Generated by Nutri Intelligence Transparency v1.0
        `.trim();

        navigator.clipboard.writeText(summary);
        setShared(true);
        setTimeout(() => setShared(false), 2000);
    }, [uiTrace, selectedClaimIdx]);

    if (!uiTrace || !uiTrace.claims || uiTrace.claims.length === 0) return null;

    const currentClaim = uiTrace.claims[selectedClaimIdx] || uiTrace.claims[0];
    const tiers = uiTrace.tiers;

    const integrityMessage = useMemo(() => {
        if (currentClaim.isVerified && uiTrace.metrics.pubchemUsed) {
            return "Nutri verified this answer using PubChem P0 enforcement and causal safety checks.";
        }
        return "Nutri reached this answer by synthesizing available nutritional datasets and interaction models.";
    }, [currentClaim, uiTrace]);

    return (
        <div className="mt-6 border border-neutral-800 rounded-xl overflow-hidden bg-neutral-900/20 backdrop-blur-sm animate-fade-in shadow-2xl text-card-foreground">
            {/* 🛡️ Reasoning Integrity Banner */}
            <div className={`px-4 py-1.5 border-b border-neutral-800/50 flex items-center gap-2 overflow-hidden ${currentClaim.isVerified ? 'bg-green-500/5' : 'bg-neutral-900/40'
                }`}>
                <ShieldCheck className={`w-3 h-3 ${currentClaim.isVerified ? 'text-green-500' : 'text-neutral-500'}`} />
                <p className="text-[10px] font-mono uppercase tracking-tight text-neutral-400 truncate flex-1">
                    {integrityMessage}
                </p>
                <div className="flex items-center gap-3">
                    {uiTrace.status === 'provisional' && (
                        <span className="px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-500 text-[8px] font-bold animate-pulse font-mono border border-amber-500/20">
                            PROVISIONAL
                        </span>
                    )}
                    <Tooltip text="Nutri conducts internal integrity audits during reasoning to ensure no unauthorized data leakage and maximum causal alignment." />
                </div>
            </div>

            {/* Header / Trigger */}
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="w-full flex items-center justify-between p-4 hover:bg-neutral-800/30 transition-all duration-300 group"
            >
                <div className="flex items-center gap-3 text-left">
                    <div className="p-2 rounded-lg bg-accent/10 text-accent group-hover:scale-110 group-hover:bg-accent/20 transition-all duration-500">
                        <Brain className="w-4 h-4" />
                    </div>
                    <div>
                        <div className="flex items-center gap-2">
                            <h3 className="text-xs font-bold uppercase tracking-[0.15em] text-neutral-200 group-hover:text-white transition-colors">
                                How Nutri reached this answer
                            </h3>
                            <Tooltip text="Transparency View: Progressive discovery of Nutri's underlying reasoning logic." />
                        </div>
                        <p className="text-[10px] text-neutral-500 font-mono mt-0.5">
                            {Object.values(tiers).filter(t => t === 'available').length} / 4 Intelligence Tiers Active
                        </p>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <span className="text-[10px] font-mono text-neutral-600 group-hover:text-neutral-400 transition-colors uppercase">
                        {isOpen ? 'Collapse' : 'Inspect'}
                    </span>
                    <div className={`transition-transform duration-500 ${isOpen ? 'rotate-180' : ''}`}>
                        <ChevronDown className="w-4 h-4 text-neutral-600" />
                    </div>
                </div>
            </button>

            <AnimatePresence>
                {isOpen && (
                    <motion.div
                        id={`trace-content-${uiTrace.id}`}
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                        className="overflow-hidden border-t border-neutral-800"
                    >
                        {/* Control Bar */}
                        <div className="px-4 py-3 bg-neutral-950/60 border-b border-neutral-800 flex items-center justify-between text-[11px]">
                            <div className="flex items-center gap-2 text-neutral-400 group cursor-default">
                                <Info className="w-3.5 h-3.5 text-neutral-600 group-hover:text-accent transition-colors" />
                                <span>Evaluating confidence, applicability, and safety mechanisms.</span>
                                <Tooltip text="Why You're Seeing This: Transparency builds trust. By showing you our work, you can verify if Nutri's rationale aligns with your personal health goals." />
                            </div>

                            <div className="flex items-center gap-4">
                                {/* Share Button */}
                                <button
                                    onClick={(e) => { e.stopPropagation(); generateShareableSummary(); }}
                                    title="Copy a human-readable summary of this reasoning"
                                    className={`flex items-center gap-1.5 transition-colors group ${shared ? 'text-green-400' : 'text-neutral-500 hover:text-neutral-300'}`}
                                >
                                    {shared ? <Check className="w-3 h-3" /> : <Share2 className="w-3 h-3 group-hover:scale-110 transition-transform" />}
                                    <span className="font-mono uppercase tracking-tighter">{shared ? 'Shared' : 'Share Reasoning'}</span>
                                </button>

                                {/* Expert Mode Toggle */}
                                <button
                                    onClick={toggleExpertMode}
                                    title="Show clinical telemetry, histograms, and path details"
                                    className={`flex items-center gap-1.5 transition-all group ${isExpertMode ? 'text-accent' : 'text-neutral-500 hover:text-neutral-300'}`}
                                >
                                    <Settings2 className={`w-3 h-3 group-hover:rotate-45 transition-transform duration-500 ${isExpertMode ? 'animate-pulse' : ''}`} />
                                    <span className="font-mono uppercase tracking-tighter">Expert</span>
                                </button>

                                {/* Raw Export */}
                                <button
                                    onClick={(e) => { e.stopPropagation(); handleCopy(); }}
                                    title="Copy raw JSON trace data"
                                    className="flex items-center gap-1.5 text-neutral-700 hover:text-neutral-500 transition-colors group"
                                >
                                    {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
                                    <span className="font-mono uppercase tracking-tighter mt-0.5">JSON</span>
                                </button>
                            </div>
                        </div>

                        {/* Claim Selector */}
                        {uiTrace.claims.length > 1 && (
                            <div className="px-4 py-2 flex items-center gap-2 border-b border-neutral-800 bg-neutral-900/10 overflow-x-auto scrollbar-none">
                                <MessageSquare className="w-3 h-3 text-neutral-700 shrink-0 mr-1" />
                                {uiTrace.claims.map((claim, idx) => (
                                    <button
                                        key={claim.id || idx}
                                        onClick={() => handleClaimSelect(idx)}
                                        className={`shrink-0 px-3 py-1.5 rounded-lg text-[10px] font-bold transition-all duration-300 ${selectedClaimIdx === idx
                                            ? 'bg-neutral-200 text-neutral-950 shadow-[0_0_15px_rgba(255,255,255,0.1)]'
                                            : 'text-neutral-500 hover:text-neutral-300 bg-neutral-800/40 hover:bg-neutral-800'
                                            }`}
                                    >
                                        CLAIM {idx + 1}
                                    </button>
                                ))}
                            </div>
                        )}

                        {/* Main Grid Content */}
                        <div className="p-4 grid grid-cols-1 lg:grid-cols-2 gap-10 bg-neutral-900/40">
                            <div className="space-y-10">
                                <section className="animate-fade-in" style={{ animationDelay: '100ms' }}>
                                    <Tier1Evidence
                                        claim={currentClaim}
                                        metrics={uiTrace.metrics}
                                        expertMode={isExpertMode}
                                    />
                                </section>

                                {tiers.tier2 === 'available' ? (
                                    <section className="pt-10 border-t border-neutral-800/50 animate-fade-in" style={{ animationDelay: '200ms' }}>
                                        <Tier2Mechanism
                                            claim={currentClaim}
                                            expertMode={isExpertMode}
                                        />
                                    </section>
                                ) : (
                                    <div className="pt-10 border-t border-neutral-800/50 opacity-40 grayscale italic text-[10px] text-neutral-500 font-mono text-center">
                                        Mechanism chain not required for this query.
                                    </div>
                                )}
                            </div>

                            <div className="space-y-10">
                                <section className="animate-fade-in" style={{ animationDelay: '300ms' }}>
                                    <Tier3Causality
                                        uiTrace={uiTrace}
                                        claimIdx={selectedClaimIdx}
                                        expertMode={isExpertMode}
                                    />
                                </section>

                                {tiers.tier4 === 'available' ? (
                                    <section className="pt-10 border-t border-neutral-800/50 animate-fade-in" style={{ animationDelay: '400ms' }}>
                                        <Tier4Temporal
                                            uiTrace={uiTrace}
                                            claimIdx={selectedClaimIdx}
                                            expertMode={isExpertMode}
                                        />
                                    </section>
                                ) : (
                                    <div className="pt-10 border-t border-neutral-800/50 opacity-40 grayscale italic text-[10px] text-neutral-500 font-mono text-center">
                                        Intelligence state consistent with initialization.
                                    </div>
                                )}

                                <section className="pt-10 border-t border-neutral-800/50 animate-fade-in" style={{ animationDelay: '500ms' }}>
                                    <ConfidenceTracker
                                        uiTrace={uiTrace}
                                        claimIdx={selectedClaimIdx}
                                        expertMode={isExpertMode}
                                    />
                                </section>
                            </div>
                        </div>

                        {/* Advanced Telemetry Dashboard */}
                        {isExpertMode && (
                            <div className="px-5 py-8 border-t border-neutral-800 bg-neutral-950/80">
                                <div className="flex items-center gap-2 mb-6">
                                    <Cpu className="w-4 h-4 text-accent animate-pulse" />
                                    <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-neutral-400">Advanced Telemetry Dashboard</h4>
                                </div>
                                <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
                                    <div className="space-y-1.5 p-3 rounded-lg bg-neutral-900/30 border border-neutral-800/50">
                                        <p className="text-[9px] text-neutral-600 uppercase font-mono tracking-wider">RAG Coverage</p>
                                        <p className="text-base font-mono text-neutral-100 italic">{(uiTrace.metrics.moaCoverage || 0).toFixed(1)}%</p>
                                    </div>
                                    <div className="space-y-1.5 p-3 rounded-lg bg-neutral-900/30 border border-neutral-800/50">
                                        <p className="text-[9px] text-neutral-600 uppercase font-mono tracking-wider">Session Turn</p>
                                        <p className="text-base font-mono text-neutral-100">{uiTrace.temporal.turn}</p>
                                    </div>
                                    <div className="space-y-1.5 p-3 rounded-lg bg-neutral-900/30 border border-neutral-800/50">
                                        <p className="text-[9px] text-neutral-600 uppercase font-mono tracking-wider">Latency</p>
                                        <p className="text-base font-mono text-neutral-100">{uiTrace.metrics.duration}ms</p>
                                    </div>
                                    <div className="space-y-1.5 p-3 rounded-lg bg-neutral-900/30 border border-neutral-800/50">
                                        <p className="text-[9px] text-neutral-600 uppercase font-mono tracking-wider">Tracing ID</p>
                                        <p className="text-base font-mono text-neutral-100 truncate opacity-40 hover:opacity-100 transition-opacity" title={uiTrace.id}>
                                            {uiTrace.id?.substring(0, 12)}...
                                        </p>
                                    </div>
                                </div>
                            </div>
                        )}
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
});

export default NutriIntelligencePanel;
