export const SUGGESTION_POOL = [
    { id: '1', text: "Why is my carbonara grainy?", type: "Diagnostic" },
    { id: '2', text: "How to make crispy fried chicken", type: "Procedural" },
    { id: '3', text: "What makes bread fluffy?", type: "Scientific" },
    { id: '4', text: "Why did my sourdough bread not rise?", type: "Diagnostic" },
    { id: '5', text: "Perfect steak internal temperatures", type: "Procedural" },
    { id: '6', text: "The chemistry of Maillard reaction", type: "Scientific" },
    { id: '7', text: "Why is my pesto turning brown?", type: "Diagnostic" },
    { id: '8', text: "How to emulsify a perfect hollandaise", type: "Procedural" },
    { id: '9', text: "Effect of altitude on boiling points", type: "Scientific" },
    { id: '10', text: "Why is my cake dry and dense?", type: "Diagnostic" },
    { id: '11', text: "Reverse sear technique for ribeye", type: "Procedural" },
    { id: '12', text: "Protein structure in egg whites", type: "Scientific" },
    { id: '13', text: "Troubleshooting broken mayonnaise", type: "Diagnostic" },
    { id: '14', text: "Traditional Neapolitan pizza dough", type: "Procedural" },
    { id: '15', text: "pH levels in fermentation", type: "Scientific" },
    { id: '16', text: "Why does my garlic turn blue?", type: "Diagnostic" },
    { id: '17', text: "Technique for silky smooth ganache", type: "Procedural" },
    { id: '18', text: "Starch gelatinization in sauces", type: "Scientific" },
    { id: '19', text: "Why is my hummus not creamy?", type: "Diagnostic" },
    { id: '20', text: "How to clarify butter into ghee", type: "Procedural" },
    { id: '21', text: "Osmosis in meat brining", type: "Scientific" },
    { id: '22', text: "Why did my cookies spread too much?", type: "Diagnostic" }
];
